// Generated by scripts/build-web-receiver.sh — do not edit by hand.
// Content hash of public/webrx/*; appended as ?v= to bust HTTP caches
// whenever the engine artifacts change.
export const WEBRX_VERSION = "9709a01fbf0b";
